### ISSUE TITLE
add command like blueprint submit to create several components all-at-once.

### ISSUE THREAD

**Issue by cloudcheflabs** [cloudcheflabs/dataroaster#98]
a blueprint job file  `all-at-once.yaml` could be:

```
project: 
  name: a project
  description: a description
cluster: 
  name: a cluster
  description: a description
  kubeconfig: ~/.kube/config
services:
  - service: ingresscontroller
    spec:
    ...
  - service: datacatalog
    spec:
      ...
  - service: queryengine
    spec:
      ...
  - service: analytics
    spec:
    ...
  - service: streaming
    spec:
    ...
templates:
  - name: s3
    bucket: mybucket
    accessKey: my-access-key
    secretKey: my-secret-key
    endpoint: https://s3-endpoint
...
```

cli command could look like this.
```
dataroaster blueprint create --file ./all-at-once.yaml
```
